# Generated by Django 5.0.1 on 2024-01-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name_plural': 'dishes'},
        ),
    ]
