# Generated by Django 5.0.1 on 2024-01-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_dish_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdish',
            options={'ordering': ['dish', 'user'], 'verbose_name_plural': 'User dishes'},
        ),
    ]
