# Generated by Django 5.0.1 on 2024-02-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_dishimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='dishimage',
            name='dish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dish_image', serialize=False, to='dishes.dish'),
        ),
    ]
