# Generated by Django 5.0.1 on 2024-02-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_remove_dishimage_id_alter_dishimage_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='weight_cooked_grams',
            field=models.FloatField(default=0),
        ),
    ]
