# Generated by Django 5.0.1 on 2024-02-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_dish_weight_cooked_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='weight_cooked_grams',
            field=models.FloatField(default=0, verbose_name='вес готового блюда (г)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbonhydrates',
            field=models.FloatField(blank=True, null=True, verbose_name='углеводы/100г'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fats',
            field=models.FloatField(blank=True, null=True, verbose_name='жиры/100г'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='kcal',
            field=models.FloatField(blank=True, null=True, verbose_name='ккал/100г'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteins',
            field=models.FloatField(blank=True, null=True, verbose_name='белки/100г'),
        ),
    ]
